name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          pip install -r requirements.txt
          pip install -r dev_requirements.txt

      - name: Install quarto
        run: |
          # download the latest stable release of quarto
          version=$(curl https://quarto.org/docs/download/_download.json | jq -r '.version')
          echo "Installing quarto version $version"
          gh release download -R github.com/quarto-dev/quarto-cli v$version --pattern "*linux-amd64.deb"
          sudo dpkg -i quarto-${version}-linux-amd64.deb

      - name: Render
        run: |
          quarto render

      - name: Upload quarto artifact
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v4
        with:
          name: quarto-docs
          path: docs

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
      - name: Download quarto-docs artifact
        uses: actions/download-artifact@v4
        with:
          name: quarto-docs
          path: docs

      - name: Upload pages artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
